### PR TITLE
I cant edit :(

### PR DESCRIPTION
**Pull request by testbot-github**

### CODE REVIEW

**Comment by testbot-github** [comment]
u removed me from the readme? :(

**Comment by testbot-github** [comment]
I kept RLX team in server.js and u only changed to RLX/MathisCool 
and now u removed 😭

**Comment by RLX-OP** [comment]
Sorry for that actually I was checking this new bot for projects :) adding you again 
Thanks

**Comment by testbot-github** [comment]
> Sorry for that actually I was checking this new bot for projects :) adding you again Thanks

Oh...
Btw please check discord and be active instead of being inactive....

**Pull request merged**
